cc_library(
    name = "pool",
    hdrs = ["inc/pool/pool.h"],
    includes = ["inc"],
    copts = [
        "-mcpu=cortex-m4",
        "-mthumb",
        "-ffreestanding",
        "-fno-exceptions",
        "-fno-rtti",
        "-std=c++17",
    ],
    visibility = ["//fw:__subpackages__"],
)
