cc_library(
    name = "ports",
    hdrs = [
        "inc/ports/angle_sensor.h",
        "inc/ports/platform_ports.h",
    ],
    includes = ["inc"],
    copts = ["-std=c++17"],
    visibility = ["//fw:__subpackages__"],
)
